### ISSUE TITLE
Please add Dotnet 6 support

### ISSUE THREAD

**Issue by hyperlogic-dev** [saladpuk/PromptPay#10]
Hi Developer  
  Please add Dotnet 6 support
Thanks

**Comment by Sakul** [comment]
Hi hyperlogic-dev
I have plans to upgrade to version 6 in the future, but I'm very busy lately. If I have time, I'll come back and do it later.
I recommended you clone my source code and change it to .NET 6 for use as temporary.
ขอบคุณครับ

**Comment by hyperlogic-dev** [comment]
Hi Khun Sakul
 The issue is " th Region is not supported " on docker dotnet 6 -Alpine version only
but this library it's work perfecly on Dotnet 6 standard sdk.
I just change the version of dotnet from dotnet 6.0-alpine to dotnet 6.0 sdk.
ขอบคุณที่ทำ Lib ดีๆมาแชร์กับครับ
