### ISSUE TITLE
ติดตั้งไม่ผ่านครับ

### ISSUE THREAD

**Issue by chukiatt** [saladpuk/PromptPay#11]
รบกวนสอบถามครับ 
ติดตั้งบน visual studio 2015 ได้ไหมครับ

ผมลอง New Project แล้วติดตั้งผ่าน nuget มี Error แบบนี้ครับ ไม่ทราบว่าพอจะแนะนำได้ไหมครับ
ขอบคุณมากครับ

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Linq' does not exist in the namespace 'System' (are you missing an assembly reference?)	WindowsFormsApplication2	d:\visual studio 2015\Projects\WindowsFormsApplication2\WindowsFormsApplication2\Form1.cs	6	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Saladpuk.PromptPay 3.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v2.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by Sakul** [comment]
ตัว Visual Studio 2015 น่าจะใช้ไม่ได้นะครับ ขั้นต่ำน่าจะเป็น 2017 หรือ 2019 ครับผม
