### ISSUE TITLE
Response

### ISSUE THREAD

**Issue by Chaianun** [saladpuk/PromptPay#12]
API ตัวนี้มันมี Response ไหมครับ อยากทำเป็น RealTime ครับ

**Comment by Sakul** [comment]
> API ตัวนี้มันมี Response ไหมครับ อยากทำเป็น RealTime ครับ

Response หมายถึงยังไงเหรอครับ ผมอ่านแล้วยังไม่ค่อยเข้าใจ เพราะตัว lib ที่เขียนไว้ผมออกแบบให้มันเป็นกลางๆ ถ้าอ่าน/เขียน QR เสร็จก็สามารถเอาไปใช้เป็น Response อะไรก็ได้ครับ
