### ISSUE TITLE
ใช้ TagID30 ใส่ TaxID แอพ SCB, KTB สแกนไม่ผ่าน แต่ KBANK ผ่าน

### ISSUE THREAD

**Issue by rabin111** [saladpuk/PromptPay#14]
string qr = PPay.StaticQR
            .TaxId("02xxxxxxxxx23")
            .BillerSuffix("77")
            .BillRef1("1234")
            .BillRef2("5678")
            .Amount(88.88)
            .CreateBillPaymentQrCode();

จากตัวอย่างขอ ปิด TaxId ไว้ ของจริงกรอกถูกต้องได้ QR Code มาแล้ว แต่ Scan ได้แค่ App KBANK ส่วน App อื่น SCB, KTB, KMA, BBL ขึ้นว่ารูปแบบไม่ถูกต้องครับ

**Comment by Sakul** [comment]
กำลังตรวจสอบให้นะครับ

**Comment by Sakul** [comment]
เท่าที่ลองเช็คแล้วฝั่งผมใช้งานได้หมดนะครับ ซึ่งเดาว่าเคสที่เกิดขึ้นอาจเกิดจากเป็น BillerId ที่ KBank สร้างให้ เลยทำให้ธนาคารอื่นๆอ่านไม่ได้ครับ รบกวนขอข้อมูลส่วนนี้เพิ่มด้วยนะครับจะได้ช่วยดูต่อให้
